package com.mycompany.kahootapp;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Kahootwindow extends javax.swing.JFrame {

    String frage[] = new String[10];
    String antwort1[] = new String[10];
    String antwort2[] = new String[10];
    String antwort3[] = new String[10];
    String antwort4[] = new String[10];
    int richtig[] = new int[10];
    boolean p;
    int spielerzahl = 0;

    String spielername[] = new String[101];
    int punkt[] = new int[101];
    int punktezaehle = 0;
    int punkte = 0;
    int nummer = 0;

    String[] satz = {"Sie Können jetzt mit Spielen anfangen\n VIEL SPAß :)",
        "Achtung! Sie MUSSEN zuerst Ihren Name Schreiben.",
        " Wählen Sie entwieder Nächster Spieler, oder Info! ",
        "Achtung! Wie vorher... Sie mussen zuerst Ihren Name schreiben, Sonst klicken Sie auf EXIT",};

    public Kahootwindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        exit1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Antwort4 = new javax.swing.JButton();
        Antwort1 = new javax.swing.JButton();
        Antwort2 = new javax.swing.JButton();
        Antwort3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        OK1 = new javax.swing.JButton();
        Name1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Frage = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Start = new javax.swing.JButton();
        NaechsterFrage = new javax.swing.JButton();
        NaechsteSpieler = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Ausgabe1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area1 = new javax.swing.JTextArea();
        INFOS = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        exit1.setBackground(new java.awt.Color(255, 0, 0));
        exit1.setFont(new java.awt.Font("PT Serif", 3, 16)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 255, 255));
        exit1.setText("EXIT");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(exit1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kahootapp");
        setBackground(new java.awt.Color(153, 51, 255));
        setForeground(new java.awt.Color(153, 51, 255));

        jPanel1.setBackground(new java.awt.Color(175, 107, 235));

        Antwort4.setBackground(new java.awt.Color(153, 51, 255));
        Antwort4.setFont(new java.awt.Font("PT Serif", 3, 22)); // NOI18N
        Antwort4.setText("Antwort4");
        Antwort4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Antwort4ActionPerformed(evt);
            }
        });

        Antwort1.setBackground(new java.awt.Color(153, 51, 255));
        Antwort1.setFont(new java.awt.Font("PT Serif", 3, 22)); // NOI18N
        Antwort1.setText("Antwort1");
        Antwort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Antwort1ActionPerformed(evt);
            }
        });

        Antwort2.setBackground(new java.awt.Color(153, 51, 255));
        Antwort2.setFont(new java.awt.Font("PT Serif", 3, 22)); // NOI18N
        Antwort2.setText("Antwort2");
        Antwort2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Antwort2ActionPerformed(evt);
            }
        });

        Antwort3.setBackground(new java.awt.Color(153, 51, 255));
        Antwort3.setFont(new java.awt.Font("PT Serif", 3, 22)); // NOI18N
        Antwort3.setText("Antwort3");
        Antwort3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Antwort3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Antwort3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Antwort1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Antwort2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Antwort4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Antwort1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(Antwort2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Antwort3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Antwort4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(175, 107, 235));

        jLabel3.setFont(new java.awt.Font("PT Serif", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name der Spieler/in:");

        OK1.setBackground(new java.awt.Color(153, 51, 255));
        OK1.setFont(new java.awt.Font("PT Serif", 3, 16)); // NOI18N
        OK1.setText("OK");
        OK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK1ActionPerformed(evt);
            }
        });

        Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(OK1))
                    .addComponent(Name1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OK1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(175, 107, 235));

        Frage.setBackground(new java.awt.Color(204, 204, 255));
        Frage.setFont(new java.awt.Font("PT Serif", 3, 22)); // NOI18N
        Frage.setForeground(new java.awt.Color(255, 255, 255));
        Frage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Frage.setText("Frage");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Frage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Frage, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(175, 107, 235));

        Start.setBackground(new java.awt.Color(153, 51, 255));
        Start.setFont(new java.awt.Font("PT Serif", 3, 16)); // NOI18N
        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        NaechsterFrage.setBackground(new java.awt.Color(153, 51, 255));
        NaechsterFrage.setFont(new java.awt.Font("PT Serif", 3, 16)); // NOI18N
        NaechsterFrage.setText("Nächster Frage");
        NaechsterFrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaechsterFrageActionPerformed(evt);
            }
        });

        NaechsteSpieler.setBackground(new java.awt.Color(153, 51, 255));
        NaechsteSpieler.setFont(new java.awt.Font("PT Serif", 3, 16)); // NOI18N
        NaechsteSpieler.setText("Nächster Spieler");
        NaechsteSpieler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaechsteSpielerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NaechsteSpieler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NaechsterFrage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NaechsterFrage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NaechsteSpieler)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(175, 107, 235));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("PT Serif", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanel7.setBackground(new java.awt.Color(175, 107, 235));

        Ausgabe1.setBackground(new java.awt.Color(153, 51, 255));
        Ausgabe1.setFont(new java.awt.Font("PT Serif", 3, 24)); // NOI18N
        Ausgabe1.setForeground(new java.awt.Color(255, 255, 255));
        Ausgabe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ausgabe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ausgabe1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(175, 107, 235));

        jScrollPane1.setBackground(new java.awt.Color(153, 51, 255));

        Area1.setBackground(new java.awt.Color(204, 204, 255));
        Area1.setColumns(20);
        Area1.setFont(new java.awt.Font("PT Serif", 3, 18)); // NOI18N
        Area1.setRows(5);
        jScrollPane1.setViewportView(Area1);

        INFOS.setBackground(new java.awt.Color(255, 255, 255));
        INFOS.setFont(new java.awt.Font("PT Serif", 3, 16)); // NOI18N
        INFOS.setText("infos");
        INFOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(INFOS, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(INFOS))
        );

        jPanel9.setBackground(new java.awt.Color(175, 107, 235));

        jLabel1.setBackground(new java.awt.Color(153, 51, 255));
        jLabel1.setFont(new java.awt.Font("PT Serif", 3, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KAHOOT!");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void Antwort4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Antwort4ActionPerformed
        if (richtig[nummer] == 3) {
            Ausgabe1.setText("Richtig");
            Antwort1.setEnabled(false);
            Antwort2.setEnabled(false);
            Antwort3.setEnabled(false);
            //Antwort4.setEnabled(false);
            punkte++;

            Antwort4.setBackground(Color.GREEN);
        } else {
            Ausgabe1.setText("Falsch!");
            Antwort1.setEnabled(false);
            Antwort2.setEnabled(false);
            Antwort3.setEnabled(false);
            Antwort4.setEnabled(false);

            Antwort1.setBackground(Color.red);
            Antwort2.setBackground(Color.red);
            Antwort3.setBackground(Color.red);
        }

    }//GEN-LAST:event_Antwort4ActionPerformed

    private void Antwort3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Antwort3ActionPerformed
        if (richtig[nummer] == 2) {
            Ausgabe1.setText("Richtig");
            Antwort1.setEnabled(false);
            Antwort2.setEnabled(false);
            //Antwort3.setEnabled(false);
            Antwort4.setEnabled(false);
            punkte++;

            Antwort3.setBackground(Color.GREEN);
        } else {
            Ausgabe1.setText("Falsch!");
            Antwort1.setEnabled(false);
            Antwort2.setEnabled(false);
            Antwort3.setEnabled(false);
            Antwort4.setEnabled(false);

            Antwort1.setBackground(Color.red);
            Antwort2.setBackground(Color.red);
            Antwort4.setBackground(Color.red);

        }

    }//GEN-LAST:event_Antwort3ActionPerformed

    private void Antwort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Antwort1ActionPerformed
        if (richtig[nummer] == 0) {
            Ausgabe1.setText("Richtig");
            //Antwort1.setEnabled(false);
            Antwort2.setEnabled(false);
            Antwort3.setEnabled(false);
            Antwort4.setEnabled(false);
            punkte++;

            Antwort1.setBackground(Color.GREEN);

        } else {
            Ausgabe1.setText("Falsch!");
            Antwort1.setEnabled(false);
            Antwort2.setEnabled(false);
            Antwort3.setEnabled(false);
            Antwort4.setEnabled(false);

            Antwort2.setBackground(Color.red);
            Antwort3.setBackground(Color.red);
            Antwort4.setBackground(Color.red);

        }

    }//GEN-LAST:event_Antwort1ActionPerformed

    private void Antwort2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Antwort2ActionPerformed
        if (richtig[nummer] == 1) {
            Ausgabe1.setText("Richtig");
            Antwort1.setEnabled(false);
            //Antwort2.setEnabled(false);
            Antwort3.setEnabled(false);
            Antwort4.setEnabled(false);
            punkte++;

            Antwort2.setBackground(Color.GREEN);
        } else {
            Ausgabe1.setText("Falsch!");
            Antwort1.setEnabled(false);
            Antwort2.setEnabled(false);
            Antwort3.setEnabled(false);
            Antwort4.setEnabled(false);

            Antwort1.setBackground(Color.red);
            Antwort3.setBackground(Color.red);
            Antwort4.setBackground(Color.red);

        }

    }//GEN-LAST:event_Antwort2ActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed

        frage[0] = "Wie viel sekunde hat ein Jahr? ";
        antwort1[0] = "31 556 000 sec.";
        antwort2[0] = "31 536 000 sec.";
        antwort3[0] = "31 537 000 sec.";
        antwort4[0] = "31 540 000 sec.";
        richtig[0] = 1;

        frage[1] = "Wie viel einwohner hat Essen (in 2016)? ";
        antwort1[1] = "582.642 einwohner";
        antwort2[1] = "582.724 einwohner";
        antwort3[1] = "582.624 einwohner";
        antwort4[1] = "582.264 einwohner";
        richtig[1] = 2;

        frage[2] = "Wer hat der Programmiersprache Java erfunden? ";
        antwort1[2] = "James Gosling";
        antwort2[2] = "Bjarne Stroustrup";
        antwort3[2] = "Dennis Ritchie";
        antwort4[2] = "Massimo Banzi und David Cuartielles";
        richtig[2] = 1;

        frage[3] = "Wer hat den Begriff Software prägte? ";
        antwort1[3] = "John William Mauchly ";
        antwort2[3] = "John W. Tukey";
        antwort3[3] = "John Presper Eckert ";
        antwort4[3] = "Oder alle drei";
        richtig[3] = 1;

        frage[4] = "Wer hat das erste Fernsehen erfunden? ";
        antwort1[4] = "Philo Farnsworth";
        antwort2[4] = "Charles Francis Jenkins";
        antwort3[4] = "John Logie Baird";
        antwort4[4] = "Oder alle drei";
        richtig[4] = 3;

        frage[5] = "Wer hat das erste Radio erfunden? ";
        antwort1[5] = "William Dubilier";
        antwort2[5] = "Guglielmo Marconi";
        antwort3[5] = "Reginald Fessenden";
        antwort4[5] = "Oder alle deri";
        richtig[5] = 3;

        frage[6] = "Wann gab es das erste Fernsehen? ";
        antwort1[6] = "1886";
        antwort2[6] = "1790";
        antwort3[6] = "1890";
        antwort4[6] = "1900";
        richtig[6] = 0;

        frage[7] = "Wann gab es den ersten Computer? ";
        antwort1[7] = "1946";
        antwort2[7] = "1982";
        antwort3[7] = "1970";
        antwort4[7] = "1977";
        richtig[7] = 2;

        frage[8] = "Wie teuer war der erste PC? ";
        antwort1[8] = "150.000 Dollar ";
        antwort2[8] = "500.000 Dollar ";
        antwort3[8] = "300.000 Dollar ";
        antwort4[8] = "450.000 Dollar ";
        richtig[8] = 1;

        frage[9] = "Wie viel PCs werden in Deutschland jährlich verkaufen? ";
        antwort1[9] = "rund 5 Millionen PCs";
        antwort2[9] = "rund 8 Millionen PCs";
        antwort3[9] = "rund 10 Millionen PCs";
        antwort4[9] = "rund 12 Millionen PCs";
        richtig[9] = 2;

        Frage.setText(frage[nummer]);
        Antwort1.setText(antwort1[nummer]);
        Antwort2.setText(antwort2[nummer]);
        Antwort3.setText(antwort3[nummer]);
        Antwort4.setText(antwort4[nummer]);

        NaechsterFrage.setEnabled(false);
        NaechsteSpieler.setEnabled(false);
        OK1.setEnabled(true);
        Start.setEnabled(false);
        INFOS.setEnabled(false);

        Antwort1.setEnabled(false);
        Antwort2.setEnabled(false);
        Antwort3.setEnabled(false);
        Antwort4.setEnabled(false);

        Ausgabe1.setText("" + satz[1]);
    }//GEN-LAST:event_StartActionPerformed

    private void NaechsterFrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaechsterFrageActionPerformed
        nummer++;

        if (nummer < 10) {
            Frage.setText(frage[nummer]);
            Antwort1.setText(antwort1[nummer]);
            Antwort2.setText(antwort2[nummer]);
            Antwort3.setText(antwort3[nummer]);
            Antwort4.setText(antwort4[nummer]);

            Ausgabe1.setText("");

        } else {
            if (punkte >= 0) {
                punktezaehle++;
                for (int i = 0; i <= punkte; i++) {
                    punkt[punktezaehle] = punkte;
                }
                punkte = 0;
            }
            Frage.setText("");
            Antwort1.setText("");
            Antwort2.setText("");
            Antwort3.setText("");
            Antwort4.setText("");

            Start.setEnabled(false);
            INFOS.setEnabled(true);
            OK1.setEnabled(false);
            NaechsterFrage.setEnabled(false);
            NaechsteSpieler.setEnabled(true);

            Ausgabe1.setText("" + satz[2]);

        }
        Antwort1.setEnabled(true);
        Antwort2.setEnabled(true);
        Antwort3.setEnabled(true);
        Antwort4.setEnabled(true);

        Antwort1.setBackground(Color.LIGHT_GRAY);
        Antwort2.setBackground(Color.LIGHT_GRAY);
        Antwort3.setBackground(Color.LIGHT_GRAY);
        Antwort4.setBackground(Color.LIGHT_GRAY);


    }//GEN-LAST:event_NaechsterFrageActionPerformed

    private void OK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK1ActionPerformed

        spielerzahl++;

        for (int i = 0; i < spielerzahl; i++) {
            spielername[spielerzahl] = Name1.getText();
        }

        NaechsterFrage.setEnabled(true);
        NaechsteSpieler.setEnabled(false);
        OK1.setEnabled(false);
        Start.setEnabled(false);
        INFOS.setEnabled(false);

        Antwort1.setEnabled(true);
        Antwort2.setEnabled(true);
        Antwort3.setEnabled(true);
        Antwort4.setEnabled(true);

        Ausgabe1.setText("" + satz[0]);
        Name1.setText(" ");


    }//GEN-LAST:event_OK1ActionPerformed

    private void NaechsteSpielerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaechsteSpielerActionPerformed

        nummer = 0;
        Ausgabe1.setText("" + satz[2]);

        NaechsterFrage.setEnabled(false);
        NaechsteSpieler.setEnabled(false);
        OK1.setEnabled(false);
        Start.setEnabled(true);
        INFOS.setEnabled(false);

        Antwort1.setEnabled(false);
        Antwort2.setEnabled(false);
        Antwort3.setEnabled(false);
        Antwort4.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_NaechsteSpielerActionPerformed

    private void INFOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFOSActionPerformed

        for (int i = 1; i <= spielerzahl; i++) {

            Area1.append(i + ". mitSpieler: " + spielername[i] + ", Punkte: " + punkt[i] + " \n");

        }
        NaechsterFrage.setEnabled(false);
        NaechsteSpieler.setEnabled(false);
        OK1.setEnabled(false);
        Start.setEnabled(false);
        INFOS.setEnabled(false);


    }//GEN-LAST:event_INFOSActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit1ActionPerformed

    private void Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kahootwindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kahootwindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kahootwindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kahootwindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kahootwindow().setVisible(true);

            }

        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Antwort1;
    private javax.swing.JButton Antwort2;
    private javax.swing.JButton Antwort3;
    private javax.swing.JButton Antwort4;
    private javax.swing.JTextArea Area1;
    private javax.swing.JLabel Ausgabe1;
    private javax.swing.JLabel Frage;
    private javax.swing.JButton INFOS;
    private javax.swing.JButton NaechsteSpieler;
    private javax.swing.JButton NaechsterFrage;
    private javax.swing.JTextField Name1;
    private javax.swing.JButton OK1;
    private javax.swing.JButton Start;
    private javax.swing.JButton exit1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
